// @generated by scripts/generate-animation-timings.mjs. Do not edit manually.

pub const FLOAT_HEART_REMOVAL_MS: i32 = 800;
pub const SPARKLE_REVEAL_MS: i32 = 600;
pub const JELLY_WOBBLE_MS: i32 = 600;
