//! Asset manifest loading module
//! Replaces hardcoded static asset paths with JSON manifest
//! Manifest generated at build time by .trunk/asset-manifest.sh

use once_cell::sync::Lazy;
use serde::Deserialize;
use std::collections::HashMap;
use web_sys::console;

/// Asset manifest structure (matches public/asset-manifest.json)
#[derive(Deserialize, Debug)]
struct AssetManifest {
    companions: HashMap<String, String>,
    gardens: HashMap<String, String>,
}

/// Embedded asset manifest (compiled into binary)
/// Generated by .trunk/asset-manifest.sh before Rust compilation
const MANIFEST_JSON: &str = include_str!("../public/asset-manifest.json");

/// Lazily parsed asset manifest
static ASSET_MANIFEST: Lazy<AssetManifest> = Lazy::new(|| {
    match serde_json::from_str(MANIFEST_JSON) {
        Ok(manifest) => manifest,
        Err(e) => {
            console::error_1(&format!("[assets] Failed to parse manifest: {:?}", e).into());
            // Return empty manifest as fallback
            AssetManifest {
                companions: HashMap::new(),
                gardens: HashMap::new(),
            }
        }
    }
});

/// Get companion asset path by skin and expression
/// Returns path like "assets/companions/unicorn_happy.webp"
pub fn get_companion_asset(skin: &str, expression: &str) -> Option<&'static str> {
    let key = format!("{}_{}", skin, expression);
    ASSET_MANIFEST
        .companions
        .get(&key)
        .map(|s| {
            // SAFETY: Extends String slice lifetime to 'static. This is safe because:
            //
            // 1. ASSET_MANIFEST is a static that lives for the entire program
            // 2. The HashMap is NEVER mutated after build_manifest() completes at startup
            // 3. HashMap's internal String storage is stable (no reallocation happens)
            // 4. Single-threaded WASM prevents concurrent modification
            //
            // This optimization avoids cloning asset paths on every lookup (18 companion
            // assets × expressions + 60 garden assets = ~100 lookups during boot).
            // Without this, each lookup would clone a ~40-byte String.
            //
            // MUTATION INVARIANT: If any code path adds `.insert()`, `.remove()`, or
            // `.clear()` calls to ASSET_MANIFEST after initialization, this is UNSOUND.
            unsafe { &*(s.as_str() as *const str) }
        })
}

/// Get garden asset path by garden and stage
/// Returns path like "assets/gardens/bunny_stage_3.webp"
pub fn get_garden_asset(garden: &str, stage: u32) -> Option<&'static str> {
    let key = format!("{}_stage_{}", garden, stage);
    ASSET_MANIFEST
        .gardens
        .get(&key)
        .map(|s| {
            // SAFETY: Same safety invariants as get_companion_asset() above.
            // The gardens HashMap is also never mutated after initialization.
            unsafe { &*(s.as_str() as *const str) }
        })
}

/// Get all 5 stage assets for a garden
/// Returns array of paths for stages 1-5
#[allow(dead_code)]  // Reserved for future batch preloading
pub fn get_garden_stages(garden: &str) -> [Option<&'static str>; 5] {
    [
        get_garden_asset(garden, 1),
        get_garden_asset(garden, 2),
        get_garden_asset(garden, 3),
        get_garden_asset(garden, 4),
        get_garden_asset(garden, 5),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_companion_asset_lookup() {
        let asset = get_companion_asset("unicorn", "happy");
        assert_eq!(asset, Some("assets/companions/unicorn_happy.webp"));
    }

    #[test]
    fn test_garden_asset_lookup() {
        let asset = get_garden_asset("bunny", 3);
        assert_eq!(asset, Some("assets/gardens/bunny_stage_3.webp"));
    }

    #[test]
    fn test_garden_stages() {
        let stages = get_garden_stages("bunny");
        assert_eq!(stages[0], Some("assets/gardens/bunny_stage_1.webp"));
        assert_eq!(stages[4], Some("assets/gardens/bunny_stage_5.webp"));
    }
}
