// @generated by scripts/generate-db-contract.mjs. Do not edit manually.

pub const DB_WORKER_API_VERSION: u16 = 1;
#[allow(dead_code)]
pub const DB_WORKER_MIN_CLIENT_API_VERSION: u16 = 1;
pub const DB_SCHEMA_VERSION: u16 = 2;
pub const EXPORT_FORMAT_VERSION: u16 = 2;
