// @generated by scripts/generate-panel-registry.mjs. Do not edit manually.

pub const PANEL_REGISTRY: &[PanelMeta] = &[
    PanelMeta {
        id: "home-scene",
        narration_phrase: None,
        first_visit_tip: None,
        sound_key: None,
    },
    PanelMeta {
        id: "panel-adventures",
        narration_phrase: Some("Adventures!"),
        first_visit_tip: None,
        sound_key: Some("magic_wand"),
    },
    PanelMeta {
        id: "panel-games",
        narration_phrase: Some("Let's play!"),
        first_visit_tip: Some("Let's play a game together!"),
        sound_key: Some("chime"),
    },
    PanelMeta {
        id: "panel-gardens",
        narration_phrase: Some("Your gardens!"),
        first_visit_tip: Some("Watch your gardens grow with kindness!"),
        sound_key: Some("gentle"),
    },
    PanelMeta {
        id: "panel-mystuff",
        narration_phrase: Some("My Stuff!"),
        first_visit_tip: None,
        sound_key: Some("sparkle"),
    },
    PanelMeta {
        id: "panel-progress",
        narration_phrase: Some("My week!"),
        first_visit_tip: None,
        sound_key: None,
    },
    PanelMeta {
        id: "panel-quests",
        narration_phrase: Some("Let's do a quest!"),
        first_visit_tip: Some("These are your adventures for today!"),
        sound_key: Some("fanfare"),
    },
    PanelMeta {
        id: "panel-rewards",
        narration_phrase: Some("Your stickers!"),
        first_visit_tip: Some("Your stickers live here!"),
        sound_key: Some("sparkle"),
    },
    PanelMeta {
        id: "panel-stories",
        narration_phrase: Some("Story time!"),
        first_visit_tip: Some("Pick a story and I'll read it to you!"),
        sound_key: Some("dreamy"),
    },
    PanelMeta {
        id: "panel-tracker",
        narration_phrase: Some("Be Kind!"),
        first_visit_tip: Some("Tap a heart to be kind!"),
        sound_key: Some("gentle"),
    },
];
