// @generated by scripts/generate-skill-taxonomy.mjs. Do not edit manually.

#[allow(dead_code)]
pub const SKILL_TAXONOMY_VERSION: u16 = 1;

pub const CANONICAL_SKILLS: &[&str] = &["hug", "sharing", "helping", "love"];

#[allow(dead_code)]
pub const SKILL_ALIASES: &[(&str, &str)] = &[("nice-words", "love"), ("unicorn", "love")];

pub const SKILL_MASTERY_BRONZE_THRESHOLD: u32 = 10;
pub const SKILL_MASTERY_SILVER_THRESHOLD: u32 = 25;
pub const SKILL_MASTERY_GOLD_THRESHOLD: u32 = 50;
#[allow(dead_code)]
pub const SKILL_MASTERY_PLATINUM_THRESHOLD: u32 = 100;

pub fn canonicalize_skill(skill: &str) -> &'static str {
    match skill {
        "hug" => "hug",
        "sharing" => "sharing",
        "helping" => "helping",
        "love" => "love",
        "nice-words" => "love",
        "unicorn" => "love",
        _ => "love",
    }
}

pub fn skill_label(skill: &str) -> &'static str {
    match canonicalize_skill(skill) {
        "hug" => "Hugging",
        "sharing" => "Sharing",
        "helping" => "Helping",
        "love" => "Showing Love",
        _ => "Showing Love",
    }
}

#[allow(dead_code)]
pub fn skill_badge_noun(skill: &str) -> &'static str {
    match canonicalize_skill(skill) {
        "hug" => "Hugger",
        "sharing" => "Sharer",
        "helping" => "Helper",
        "love" => "Lover",
        _ => "Lover",
    }
}

pub fn skill_quest_indices(skill: &str) -> &'static [usize] {
    match canonicalize_skill(skill) {
        "hug" => &[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
        "sharing" => &[14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
        "helping" => &[28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
        "love" => &[56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        _ => &[],
    }
}
