use super::*;

#[derive(Clone, Copy)]
pub(super) struct PwaStatusState {
    pub(super) status: RwSignal<ImportStatus>,
    pub(super) storage: RwSignal<Option<StorageInfo>>,
    pub(super) online: RwSignal<bool>,
    pub(super) update_ready: RwSignal<bool>,
    pub(super) update_version: RwSignal<Option<String>>,
    pub(super) update_snoozed: RwSignal<bool>,
    pub(super) update_snooze_remaining: RwSignal<Option<f64>>,
    pub(super) update_checking: RwSignal<bool>,
    pub(super) update_last_checked: RwSignal<Option<f64>>,
    pub(super) update_state: RwSignal<Option<String>>,
    pub(super) update_applying: RwSignal<bool>,
    pub(super) update_error: RwSignal<Option<String>>,
    pub(super) sw_version: RwSignal<Option<String>>,
    pub(super) sw_activated_at: RwSignal<Option<f64>>,
    pub(super) sw_controller_url: RwSignal<Option<String>>,
    pub(super) sw_controller_state: RwSignal<Option<String>>,
    pub(super) sw_controller_impl: RwSignal<Option<String>>,
    pub(super) sw_controller_cache_prefix: RwSignal<Option<String>>,
    pub(super) sw_scope: RwSignal<Option<String>>,
    #[cfg_attr(not(feature = "hydrate"), allow(dead_code))]
    pub(super) previous_cache_cleaned_at: RwSignal<Option<f64>>,
    pub(super) previous_cache_cleanup: RwSignal<Option<String>>,
    pub(super) cache_entries: RwSignal<Option<usize>>,
    pub(super) storage_warning: RwSignal<Option<String>>,
    pub(super) ann_cap_override: RwSignal<Option<u64>>,
    pub(super) ai_config_version: RwSignal<Option<String>>,
    pub(super) ai_config_generated_at: RwSignal<Option<String>>,
    pub(super) embedding_sample_enabled: RwSignal<Option<bool>>,
    pub(super) ai_config_status: RwSignal<Option<String>>,
    pub(super) manifest_diff: RwSignal<Option<crate::data::ManifestDiff>>,
    pub(super) integrity_report: RwSignal<Option<crate::data::IntegrityReport>>,
    pub(super) sqlite_parity: RwSignal<Option<crate::data::SqliteParityReport>>,
    pub(super) sw_action_status: RwSignal<Option<String>>,
    pub(super) perf_metrics: RwSignal<Option<crate::browser::perf::InpMetricsSnapshot>>,
    pub(super) import_tuning_enabled: RwSignal<bool>,
    pub(super) install_prompt: RwSignal<crate::browser::pwa::InstallPromptState>,
    pub(super) install_status: RwSignal<Option<String>>,
}

impl PwaStatusState {
    pub(super) fn new() -> Self {
        Self {
            status: RwSignal::new(ImportStatus {
                message: "Checking offline data…".to_string(),
                ..Default::default()
            }),
            storage: RwSignal::new(None::<StorageInfo>),
            online: RwSignal::new(true),
            update_ready: RwSignal::new(false),
            update_version: RwSignal::new(None::<String>),
            update_snoozed: RwSignal::new(false),
            update_snooze_remaining: RwSignal::new(None::<f64>),
            update_checking: RwSignal::new(false),
            update_last_checked: RwSignal::new(None::<f64>),
            update_state: RwSignal::new(None::<String>),
            update_applying: RwSignal::new(false),
            update_error: RwSignal::new(None::<String>),
            sw_version: RwSignal::new(None::<String>),
            sw_activated_at: RwSignal::new(None::<f64>),
            sw_controller_url: RwSignal::new(None::<String>),
            sw_controller_state: RwSignal::new(None::<String>),
            sw_controller_impl: RwSignal::new(None::<String>),
            sw_controller_cache_prefix: RwSignal::new(None::<String>),
            sw_scope: RwSignal::new(None::<String>),
            previous_cache_cleaned_at: RwSignal::new(None::<f64>),
            previous_cache_cleanup: RwSignal::new(None::<String>),
            cache_entries: RwSignal::new(None::<usize>),
            storage_warning: RwSignal::new(None::<String>),
            ann_cap_override: RwSignal::new(None::<u64>),
            ai_config_version: RwSignal::new(None::<String>),
            ai_config_generated_at: RwSignal::new(None::<String>),
            embedding_sample_enabled: RwSignal::new(None::<bool>),
            ai_config_status: RwSignal::new(None::<String>),
            manifest_diff: RwSignal::new(None::<crate::data::ManifestDiff>),
            integrity_report: RwSignal::new(None::<crate::data::IntegrityReport>),
            sqlite_parity: RwSignal::new(None::<crate::data::SqliteParityReport>),
            sw_action_status: RwSignal::new(None::<String>),
            perf_metrics: RwSignal::new(None::<crate::browser::perf::InpMetricsSnapshot>),
            import_tuning_enabled: RwSignal::new(false),
            // Keep initial hydrate state aligned with SSR markup; populate browser-specific
            // install prompt details after hydration completes.
            install_prompt: RwSignal::new(crate::browser::pwa::InstallPromptState::default()),
            install_status: RwSignal::new(None::<String>),
        }
    }
}
